### ISSUE TITLE
NameError: name 'get_neighbors' is not defined

### ISSUE THREAD

**Issue by fmandel98** [VIS-WA/custom-image-similarity-faiss#1]
function get_neighbors is not specified in the notebook.

**Comment by VIS-WA** [comment]
The function is missed somehow. It is fixed with this latest [commit](https://github.com/VIS-WA/custom-image-similarity-faiss/commit/53bd8d0c5d6dcd348a10339f4fea178282d54ee2?diff=split). Thanks for raising the issue!
